dataSources:
    KauiokpooTaigiSutian:
        type: CHHOE_TAIGI_DATABASE
        path: "ChhoeTaigiDatabase/ChhoeTaigiDatabase/ChhoeTaigi_KauiokpooTaigiSutian.csv"
        parseMethods:
            - parse_single_word_v2
            - parse_single_word_from_phrase
            - parse_simple_phrase
            - parse_bun5_peh_im_phrase
            - parse_khiunn_khau2_tsha_phrase
        postProcessing:
            - convert_key_to_lower_case
            - add_no_tone
    iTaigiHoataiTuichiautian:
        type: CHHOE_TAIGI_DATABASE
        path: "ChhoeTaigiDatabase/ChhoeTaigiDatabase/ChhoeTaigi_iTaigiHoataiTuichiautian.csv"
        parseMethods:
            - parse_single_word_v2
            - parse_single_word_from_phrase
            - parse_simple_phrase
            - parse_bun5_peh_im_phrase
            - parse_khiunn_khau2_tsha_phrase
        postProcessing:
            - convert_key_to_lower_case
            - add_no_tone
    TaihoaSoanntengTuichiautian:
        type: CHHOE_TAIGI_DATABASE
        path: "ChhoeTaigiDatabase/ChhoeTaigiDatabase/ChhoeTaigi_TaihoaSoanntengTuichiautian.csv"
        parseMethods:
            - parse_single_word_v2
            - parse_single_word_from_phrase
            - parse_simple_phrase
            - parse_bun5_peh_im_phrase
            - parse_khiunn_khau2_tsha_phrase
        postProcessing:
            - convert_key_to_lower_case
            - add_no_tone
    TaijitToaSutian:
        type: CHHOE_TAIGI_DATABASE
        path: "ChhoeTaigiDatabase/ChhoeTaigiDatabase/ChhoeTaigi_TaijitToaSutian.csv"
        parseMethods:
            - parse_single_word_v2
            - parse_single_word_from_phrase
            - parse_simple_phrase
            - parse_bun5_peh_im_phrase
            - parse_khiunn_khau2_tsha_phrase
        postProcessing:
            - convert_key_to_lower_case
            - add_no_tone
            # TODO: implement drop_illegal_words to ignore word contains vxyz etc.
            # - drop_illegal_words
    EmbreeTaiengSutian:
        type: CHHOE_TAIGI_DATABASE
        path: "ChhoeTaigiDatabase/ChhoeTaigiDatabase/ChhoeTaigi_EmbreeTaiengSutian.csv"
        parseMethods:
            - parse_single_word_from_phrase
            - parse_simple_phrase
        postProcessing:
            - convert_key_to_lower_case
            - add_no_tone
            # - drop_illegal_words
    KamJitian:
        type: CHHOE_TAIGI_DATABASE
        path: "ChhoeTaigiDatabase/ChhoeTaigiDatabase/ChhoeTaigi_KamJitian.csv"
        parseMethods:
            - parse_single_word_v2
            # TODO: below didn't catch any entries, debug if there is an issue.
            # - parse_single_word_from_phrase
            # - parse_simple_phrase
            # - parse_bun5_peh_im_phrase
            # - parse_khiunn_khau2_tsha_phrase
        postProcessing:
            - convert_key_to_lower_case
            - add_no_tone
    MaryknollTaiengSutian:
        type: CHHOE_TAIGI_DATABASE
        path: "ChhoeTaigiDatabase/ChhoeTaigiDatabase/ChhoeTaigi_MaryknollTaiengSutian.csv"
        parseMethods:
            - parse_single_word_v2
            - parse_single_word_from_phrase
            - parse_simple_phrase
            - parse_khiunn_khau2_tsha_phrase
        postProcessing:
            - convert_key_to_lower_case
            - add_no_tone
    TaioanPehoeKichhooGiku:
        type: CHHOE_TAIGI_DATABASE
        path: "ChhoeTaigiDatabase/ChhoeTaigiDatabase/ChhoeTaigi_TaioanPehoeKichhooGiku.csv"
        parseMethods:
            - parse_single_word_v2
            - parse_single_word_from_phrase
            - parse_simple_phrase
        postProcessing:
            - convert_key_to_lower_case
            - add_no_tone
    TaioanSitbutMialui:
        type: CHHOE_TAIGI_DATABASE
        path: "ChhoeTaigiDatabase/ChhoeTaigiDatabase/ChhoeTaigi_TaioanSitbutMialui.csv"
        parseMethods:
            - parse_single_word_v2
            - parse_single_word_from_phrase
            - parse_simple_phrase
        postProcessing:
            - convert_key_to_lower_case
            - add_no_tone
    GoogleSheet:
        type: GOOGLE_SHEET
        gsheet_key: 1BswSQsbcQTJE4i9QbtsY5c3x4i-7Y-1raC0JBN8ekIM
        sheet_name: v1
        parseMethods:
            - parse_single_word_v2
            - parse_single_word_from_phrase
            - parse_simple_phrase
            - parse_one_to_one
        postProcessing:
            - convert_key_to_lower_case
            - add_no_tone
cinOutputs:
    # new-dict:
    #     dataSources:
    #         # - KauiokpooTaigiSutian
    #         # - iTaigiHoataiTuichiautian
    #         # - TaihoaSoanntengTuichiautian
    #         # - TaijitToaSutian
    #         # - EmbreeTaiengSutian
    #         # - KamJitian
    #         # - MaryknollTaiengSutian
    #         # - TaioanPehoeKichhooGiku
    #         # - TaioanSitbutMialui
    #         - GoogleSheet
    #     ename: new-dict-tailo
    #     cname: 台羅
    #     selkey: qwdzxyv
    #     out_filename: new-dict-tailo.cin
    #     include_source: True
    #     # out_dir: build/
    gsheet-dict:
        dataSources:
            - GoogleSheet
        ename: gsheet-taigi
        cname: 自訂義台羅
        selkey: qwdzxyv
        out_filename: gsheet-taigi.cin
        # include_source: True
    gsheet-dict-debug:
        dataSources:
            - GoogleSheet
        ename: gsheet-taigi-debug
        cname: 自訂義台羅
        selkey: qwdzxyv
        out_filename: gsheet-taigi-debug.cin
        include_source: True
    chhoe-taigi-dict:
        dataSources:
            - KauiokpooTaigiSutian
            - iTaigiHoataiTuichiautian
            - TaihoaSoanntengTuichiautian
            - TaijitToaSutian
            - EmbreeTaiengSutian
            - KamJitian
            - MaryknollTaiengSutian
            - TaioanPehoeKichhooGiku
            - TaioanSitbutMialui
        ename: chhoe-taigi-tailo
        cname: 揣台語台羅
        selkey: qwdzxyv
        out_filename: chhoe-taigi-tailo.cin
        # include_source: True
    chhoe-taigi-custom-dict:
        dataSources:
            - KauiokpooTaigiSutian
            - iTaigiHoataiTuichiautian
            - TaihoaSoanntengTuichiautian
            - TaijitToaSutian
            - EmbreeTaiengSutian
            - KamJitian
            - MaryknollTaiengSutian
            - TaioanPehoeKichhooGiku
            - TaioanSitbutMialui
            - GoogleSheet
        ename: chhoe-taigi-custom
        cname: 揣台語和自定義台羅
        selkey: qwdzxyv
        out_filename: chhoe-taigi-custom.cin
        # include_source: True
